name: "✨ Feature Request"
description: "Suggest an idea for this project."
title: "[FEATURE] <short description>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  - type: input
    id: feature-summary
    attributes:
      label: "Feature Summary"
      description: "Briefly describe the feature you want."
      placeholder: "A clear and concise summary of the feature."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why do you want this feature? What problem does it solve?"
      placeholder: "Explain the use case or problem."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Have you considered any alternatives?"
      placeholder: "Describe any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Context, screenshots, etc."
    validations:
      required: false
